name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - CI-CD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: CI=false npm run build

    - name: Verify root directory permissions
      run: |
        sshpass -p "${{ secrets.SFTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} "touch /testfile && rm /testfile"

    - name: Upload files via SFTP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ssh.strato.com
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_PORT }}
        source: "build/"
        target: "/"