name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - CI-CD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: CI=false npm run build
      
    - name: Upload files via SFTP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ssh.strato.com
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_PORT }}
        source: "build/static"
        target: "/static"